- name: Install nginx
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx

- shell: cat /etc/nginx/sites-enabled/default
- shell: find /usr/share/nginx/

- name: Place index
  copy:
    src: files/index.html
    dest: /usr/share/nginx/html/index.html
  notify: start and enable nginx
