- name: Install nginx
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx

- name: Place index
  copy:
    src: files/index.html
    dest: /usr/share/nginx/www/index.html
  notify: start and enable nginx
